import { Suspense } from "react";
import { Work_Sans } from "next/font/google";

import NavigationBar from "@Components/NavigationBar/NavBar";
import "../globals.scss";


const workSans = Work_Sans({ 
  weight: ['500', '600'],
  style: ['normal', 'italic'],
  subsets: ["latin"] 
});

export const metadata = {
  title: "Littardo",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }) {
  return (
    <html lang="en">
      <body className={workSans.className}><NavigationBar isNavigationShow={false} />{children}</body>
    </html>
  );
}
