import { Work_Sans } from "next/font/google";
import "../globals.scss";
import NavigationBar from "@Components/NavigationBar/NavBar";
import Footer from "@Components/Footer"

const workSans = Work_Sans({ 
  weight: ['500', '600'],
  style: ['normal', 'italic'],
  subsets: ["latin"] 
});

export const metadata = {
  title: "Littardo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={workSans.className}><NavigationBar /><main className="main" >{children}</main><Footer /></body>
      {/* className="blur-sm bg-transparents" */}
    </html>
  );
}
